name: LLM Code Validation Workflow

on:
  push:
    branches:
      - '**'  # Trigger on any branch push

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run Juice Shop tests
      run: npm test
      continue-on-error: false

    - name: Start Juice Shop server
      run: |
        npm start &
        sleep 30  # Wait for server to be ready
        echo "Server started at $(date)" >> workflow.log
        
        # Verify server is running
        for i in {1..10}; do
          if curl -f http://localhost:3000 > /dev/null 2>&1; then
            echo "Server is responding at http://localhost:3000" >> workflow.log
            break
          fi
          echo "Waiting for server to be ready... attempt $i" >> workflow.log
          sleep 5
        done
        
        # Check if server is running
        if ! curl -f http://localhost:3000 > /dev/null 2>&1; then
          echo "ERROR: Server failed to start properly" >> workflow.log
          exit 1
        fi

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: 'http://localhost:3000'
        rules_file_name: '.zap/rules.tsv'

    - name: Generate workflow summary
      run: |
        echo "=== WORKFLOW SUMMARY ===" >> workflow.log
        echo "Completed at: $(date)" >> workflow.log
        echo "Node version: $(node --version)" >> workflow.log
        echo "NPM version: $(npm --version)" >> workflow.log
        echo "Working directory: $(pwd)" >> workflow.log
        echo "Directory contents:" >> workflow.log
        ls -la >> workflow.log

    - name: Upload ZAP Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          report_html.html
          report_json.json
          report_md.md
        retention-days: 30

    - name: Upload Test Results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 30

    - name: Upload Workflow Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: workflow-logs
        path: workflow.log
        retention-days: 30
