name: Semgrep Security Scan

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Semgrep (Static Code Analysis) ---
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      continue-on-error: true
      with:
        config: p/ci
        generateSarif: true
        sarif: semgrep.sarif
        # optionally narrow scope to reduce noise
        exclude: |
          data/static/**
          ftp/**
          screenshots/**
          
    - name: Upload Semgrep SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif 
